chore(discount-rules): get discount rules by domain
ecomplus/discounts-v2 pull request #22
Opened 2024-07-23 21:05 UTC by wisley7l

2024-07-24 01:04 UTC, leomp12 requested changes

2024-07-24 01:04 UTC, leomp12 commented on functions/routes/discount-rules.js
> +    }
Tá valendo mas seria mais simples e legível com um `.filter` né
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2024-07-24 01:04 UTC, leomp12 commented on functions/routes/discount-rules.js
> +      (!rule.product_ids?.length && !rule.category_ids?.length && !rule.excluded_product_ids?.length) ||
Aqui você exclui regras que não tenham filtro além do domínio, intencional? Por que?

2024-07-24 01:04 UTC, leomp12 commented on functions/routes/discount-rules.js
> +      ((rule.utm_campaign || (rule.customer_ids && rule.customer_ids.length) || rule.discount_coupon))
👍🏾

2024-07-24 12:22 UTC, wisley7l commented on functions/routes/discount-rules.js
> +      (!rule.product_ids?.length && !rule.category_ids?.length && !rule.excluded_product_ids?.length) ||
Verdade, não há necessidade de excluir caso não tenha filtro de dominio, porque ai o lojista aplica o desconto em todos os dominios sem a necessidade de duplicar a regra.

2024-07-24 17:18 UTC, leomp12 requested changes

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +  domain = domain.replace(/https?:\/\/|:\d+/g, '')
```suggestion
  }
  domain = domain.replace(/^(https?:\/\/)?([^:/]+).*/, '$2')
```

Remover possível path ou trailing slash

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +  if (!origin || origin?.includes('localhost') || origin?.includes('127.0.0.1')) {
```suggestion
  if (!origin || origin.includes('localhost') || origin.includes('127.0.0.1')) {
```

Logo no início você testa `!origin` ué

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +const isValidRule = (rule, domain) => {
`is` indica booleano, método é imperativo, tipo `checkValidRule`...

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +  return !isInvalidRule
```suggestion
  return Boolean(
    validateDateRange(rule)
      && rule.domain === domain
      && !rule.utm_campaign
      && !rule.customer_ids?.length
      && !rule.discount_coupon
  )
```

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +      (!rule.product_ids?.length && !rule.category_ids?.length && !rule.excluded_product_ids?.length) ||
Não...

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +  return !isInvalidRule
https://github.com/ecomplus/discounts-v2/pull/22#discussion_r1688979616

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +  return !isInvalidRule
`(!rule.product_ids?.length && !rule.category_ids?.length && !rule.excluded_product_ids?.length)`

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +  return !isInvalidRule
Com isso você não permite que o lojista aplique desconto na loja toda pelo domínio

2024-07-24 17:18 UTC, leomp12 commented on functions/routes/discount-rules.js
> +  return !isInvalidRule
> Aqui você exclui regras que não tenham filtro além do domínio, intencional? Por que?

O filtro pelo domínio deve continuar sendo requerido, o que não é requerido é um filtro por item ou categoria, regras com filtro apenas pelo domínio devem passar

2024-07-24 17:20 UTC, leomp12 commented on functions/routes/discount-rules.js
> +  return !isInvalidRule
> Deu uma simplificada boa aí também né, bem mais legível sem a negação invertida

2024-07-25 00:20 UTC, leomp12 approved these changes
lgtm nelson 👍🏾

2024-07-25 00:20 UTC, merged